# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hegsy
email: amariehegarty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a final year student in Multimedia with Programming and Design. I am using this site as a way to keep my web skills sharp and as a handy place to keep track of my projects!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: amariehegarty
github_username:  hegsy

# Build settings
markdown: kramdown
