# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MM4 Final Year Project
email: amariehegarty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a final year student of the BSC in Multimedia Programming and Design, Limerick Institute of Technology. I am using this site to keep a blog for the development of my Final Year Project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hegsy.github.io" # the base hostname & protocol for your site
twitter_username: amariehegarty
github_username:  hegsy

# Build settings
markdown: kramdown
