# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anne-Marie Hegarty - Resumé
email: amariehegarty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Graduate of the BSc in Multimedia Programming and Design, Limerick Institute of Technology.
  This site previews a general version of my resumé, to highlight my skills and knowledge gained from my course.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: amariehegarty
github_username:  hegsy

# Build settings
markdown: kramdown
